


-- ----------------------------
-- Records of sys_module
-- ----------------------------
-- INSERT INTO `sys_module` (`module_id`, `parent_id`, `module_url`, `state`, `is_visible`, `actions`, `long_number`, `module_level`, `display_name`, `leaf`, `seq`, `module_name`, `module_number`, `module_description`, `creator_id`, `create_time`, `last_update_user_id`, `last_updated_time`, `ctrl_unit_id`, `module_icon`, `is_dsiplay`, `display_order`, `info1`, `info2`, `info3`, `perms`, `type`) VALUES (1477447178527, 0, 'rest/vsdtaskManage/taskManagement', '1', '1', NULL, '1477447178527', 1, '快捷菜单', 1, 4, '快捷菜单', 'taskManage', '', NULL, NULL, NULL, NULL, NULL, 'menu_2', NULL, NULL, NULL, NULL, NULL, 'menu_01_text', 'menu');
-- INSERT INTO `sys_module` (`module_id`, `parent_id`, `module_url`, `state`, `is_visible`, `actions`, `long_number`, `module_level`, `display_name`, `leaf`, `seq`, `module_name`, `module_number`, `module_description`, `creator_id`, `create_time`, `last_update_user_id`, `last_updated_time`, `ctrl_unit_id`, `module_icon`, `is_dsiplay`, `display_order`, `info1`, `info2`, `info3`, `perms`, `type`) VALUES (1477447456246, 0, 'rest/camera/cameraMgr', '1', '1', NULL, '1477447456246', 1, '综合应用', 0, 6, '综合应用', 'cameraMgr', '', NULL, NULL, NULL, NULL, NULL, 'menu_4', NULL, NULL, NULL, NULL, NULL, 'menu_02_text', 'menu');
-- INSERT INTO `sys_module` (`module_id`, `parent_id`, `module_url`, `state`, `is_visible`, `actions`, `long_number`, `module_level`, `display_name`, `leaf`, `seq`, `module_name`, `module_number`, `module_description`, `creator_id`, `create_time`, `last_update_user_id`, `last_updated_time`, `ctrl_unit_id`, `module_icon`, `is_dsiplay`, `display_order`, `info1`, `info2`, `info3`, `perms`, `type`) VALUES (1477447508878, 0, 'sysMgr', '1', '1', NULL, '1477447508878', 1, '视频任务管理', 0, 7, '视频任务管理', 'sysMgr', '', NULL, NULL, NULL, NULL, NULL, 'menu_5', NULL, NULL, NULL, NULL, NULL, 'menu_03_text', 'menu');
-- INSERT INTO `sys_module` (`module_id`, `parent_id`, `module_url`, `state`, `is_visible`, `actions`, `long_number`, `module_level`, `display_name`, `leaf`, `seq`, `module_name`, `module_number`, `module_description`, `creator_id`, `create_time`, `last_update_user_id`, `last_updated_time`, `ctrl_unit_id`, `module_icon`, `is_dsiplay`, `display_order`, `info1`, `info2`, `info3`, `perms`, `type`) VALUES (1494399173729, 0, 'rest/vsdtaskManage/largeDataSearch', '1', '1', NULL, '1494399173729', 1, '便捷管理', 0, 2, '便捷管理', 'largeDataSearch', '', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'menu_04_text', 'menu');
-- INSERT INTO `sys_module` (`module_id`, `parent_id`, `module_url`, `state`, `is_visible`, `actions`, `long_number`, `module_level`, `display_name`, `leaf`, `seq`, `module_name`, `module_number`, `module_description`, `creator_id`, `create_time`, `last_update_user_id`, `last_updated_time`, `ctrl_unit_id`, `module_icon`, `is_dsiplay`, `display_order`, `info1`, `info2`, `info3`, `perms`, `type`) VALUES (1495011517915, 1477447178527, NULL, NULL, NULL, NULL, NULL, NULL, '案件管理', NULL, NULL, '案件管理', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'menu_01_03_text,menu_01_04_text', 'menu');
-- INSERT INTO `sys_module` (`module_id`, `parent_id`, `module_url`, `state`, `is_visible`, `actions`, `long_number`, `module_level`, `display_name`, `leaf`, `seq`, `module_name`, `module_number`, `module_description`, `creator_id`, `create_time`, `last_update_user_id`, `last_updated_time`, `ctrl_unit_id`, `module_icon`, `is_dsiplay`, `display_order`, `info1`, `info2`, `info3`, `perms`, `type`) VALUES (1495011517916, 1477447178527, NULL, NULL, NULL, NULL, NULL, NULL, '目标检索', NULL, NULL, '目标检索', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'menu_01_01_text', 'menu');
-- INSERT INTO `sys_module` (`module_id`, `parent_id`, `module_url`, `state`, `is_visible`, `actions`, `long_number`, `module_level`, `display_name`, `leaf`, `seq`, `module_name`, `module_number`, `module_description`, `creator_id`, `create_time`, `last_update_user_id`, `last_updated_time`, `ctrl_unit_id`, `module_icon`, `is_dsiplay`, `display_order`, `info1`, `info2`, `info3`, `perms`, `type`) VALUES (1495011517917, 1477447178527, NULL, NULL, NULL, NULL, NULL, NULL, '跨镜追踪', NULL, NULL, '跨镜追踪', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'menu_01_02_text', 'menu');
-- INSERT INTO `sys_module` (`module_id`, `parent_id`, `module_url`, `state`, `is_visible`, `actions`, `long_number`, `module_level`, `display_name`, `leaf`, `seq`, `module_name`, `module_number`, `module_description`, `creator_id`, `create_time`, `last_update_user_id`, `last_updated_time`, `ctrl_unit_id`, `module_icon`, `is_dsiplay`, `display_order`, `info1`, `info2`, `info3`, `perms`, `type`) VALUES (1495011517918, 1477447456246, NULL, NULL, NULL, NULL, NULL, NULL, '接力追踪', NULL, NULL, '接力追踪', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'menu_02_02_text', 'menu');
-- INSERT INTO `sys_module` (`module_id`, `parent_id`, `module_url`, `state`, `is_visible`, `actions`, `long_number`, `module_level`, `display_name`, `leaf`, `seq`, `module_name`, `module_number`, `module_description`, `creator_id`, `create_time`, `last_update_user_id`, `last_updated_time`, `ctrl_unit_id`, `module_icon`, `is_dsiplay`, `display_order`, `info1`, `info2`, `info3`, `perms`, `type`) VALUES (1495011517919, 1477447508878, NULL, NULL, NULL, NULL, NULL, NULL, '添加分析任务', NULL, NULL, '添加分析任务', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'menu_03_01_text', 'menu');
-- INSERT INTO `sys_module` (`module_id`, `parent_id`, `module_url`, `state`, `is_visible`, `actions`, `long_number`, `module_level`, `display_name`, `leaf`, `seq`, `module_name`, `module_number`, `module_description`, `creator_id`, `create_time`, `last_update_user_id`, `last_updated_time`, `ctrl_unit_id`, `module_icon`, `is_dsiplay`, `display_order`, `info1`, `info2`, `info3`, `perms`, `type`) VALUES (1495011517920, 1477447508878, NULL, NULL, NULL, NULL, NULL, NULL, '专项监控组', NULL, NULL, '专项监控组', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'menu_03_04_text', 'menu');
-- INSERT INTO `sys_module` (`module_id`, `parent_id`, `module_url`, `state`, `is_visible`, `actions`, `long_number`, `module_level`, `display_name`, `leaf`, `seq`, `module_name`, `module_number`, `module_description`, `creator_id`, `create_time`, `last_update_user_id`, `last_updated_time`, `ctrl_unit_id`, `module_icon`, `is_dsiplay`, `display_order`, `info1`, `info2`, `info3`, `perms`, `type`) VALUES (1495011517921, 1494399173729, NULL, NULL, NULL, NULL, NULL, NULL, '系统管理', NULL, NULL, '系统管理', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'menu_04_01_text', 'menu');
-- INSERT INTO `sys_module` (`module_id`, `parent_id`, `module_url`, `state`, `is_visible`, `actions`, `long_number`, `module_level`, `display_name`, `leaf`, `seq`, `module_name`, `module_number`, `module_description`, `creator_id`, `create_time`, `last_update_user_id`, `last_updated_time`, `ctrl_unit_id`, `module_icon`, `is_dsiplay`, `display_order`, `info1`, `info2`, `info3`, `perms`, `type`) VALUES (1495011517925, 1477447508878, NULL, NULL, NULL, NULL, NULL, NULL, '分析任务进度查询', NULL, NULL, '分析任务进度查询', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'menu_03_02_text', 'menu');
-- INSERT INTO `sys_module` (`module_id`, `parent_id`, `module_url`, `state`, `is_visible`, `actions`, `long_number`, `module_level`, `display_name`, `leaf`, `seq`, `module_name`, `module_number`, `module_description`, `creator_id`, `create_time`, `last_update_user_id`, `last_updated_time`, `ctrl_unit_id`, `module_icon`, `is_dsiplay`, `display_order`, `info1`, `info2`, `info3`, `perms`, `type`) VALUES (1495011517926, 1495011517919, NULL, NULL, NULL, NULL, NULL, NULL, '离线视频分析', NULL, NULL, '离线视频分析', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'analysis.relinevideo', 'menu');
-- INSERT INTO `sys_module` (`module_id`, `parent_id`, `module_url`, `state`, `is_visible`, `actions`, `long_number`, `module_level`, `display_name`, `leaf`, `seq`, `module_name`, `module_number`, `module_description`, `creator_id`, `create_time`, `last_update_user_id`, `last_updated_time`, `ctrl_unit_id`, `module_icon`, `is_dsiplay`, `display_order`, `info1`, `info2`, `info3`, `perms`, `type`) VALUES (1495011517927, 1495011517919, NULL, NULL, NULL, NULL, NULL, NULL, '联网录像分析', NULL, NULL, '联网录像分析', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'analysis.onlinecamera', 'menu');
-- INSERT INTO `sys_module` (`module_id`, `parent_id`, `module_url`, `state`, `is_visible`, `actions`, `long_number`, `module_level`, `display_name`, `leaf`, `seq`, `module_name`, `module_number`, `module_description`, `creator_id`, `create_time`, `last_update_user_id`, `last_updated_time`, `ctrl_unit_id`, `module_icon`, `is_dsiplay`, `display_order`, `info1`, `info2`, `info3`, `perms`, `type`) VALUES (1495011517928, 1495011517919, NULL, NULL, NULL, NULL, NULL, NULL, '联网实时', NULL, NULL, '联网实时和IPC直连', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'analysis.onlinevideo,analysis.ipc', 'menu');
-- INSERT INTO `sys_module` (`module_id`, `parent_id`, `module_url`, `state`, `is_visible`, `actions`, `long_number`, `module_level`, `display_name`, `leaf`, `seq`, `module_name`, `module_number`, `module_description`, `creator_id`, `create_time`, `last_update_user_id`, `last_updated_time`, `ctrl_unit_id`, `module_icon`, `is_dsiplay`, `display_order`, `info1`, `info2`, `info3`, `perms`, `type`) VALUES (1495011517931, 1495011517926, NULL, NULL, NULL, NULL, NULL, NULL, '离线视频分析|上传视频', NULL, NULL, '上传', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL, 'analysis.relinevideo.uploadvideo', 'button');
-- INSERT INTO `sys_module` (`module_id`, `parent_id`, `module_url`, `state`, `is_visible`, `actions`, `long_number`, `module_level`, `display_name`, `leaf`, `seq`, `module_name`, `module_number`, `module_description`, `creator_id`, `create_time`, `last_update_user_id`, `last_updated_time`, `ctrl_unit_id`, `module_icon`, `is_dsiplay`, `display_order`, `info1`, `info2`, `info3`, `perms`, `type`) VALUES (1495011517932, 1495011517926, NULL, NULL, NULL, NULL, NULL, NULL, '离线视频分析|删除/批量删除', NULL, NULL, '删除/批量删除', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, NULL, NULL, NULL, 'analysis.relinevideo.delete,analysis.relinevideo.batchdelete', 'button');
-- INSERT INTO `sys_module` (`module_id`, `parent_id`, `module_url`, `state`, `is_visible`, `actions`, `long_number`, `module_level`, `display_name`, `leaf`, `seq`, `module_name`, `module_number`, `module_description`, `creator_id`, `create_time`, `last_update_user_id`, `last_updated_time`, `ctrl_unit_id`, `module_icon`, `is_dsiplay`, `display_order`, `info1`, `info2`, `info3`, `perms`, `type`) VALUES (1495011517934, 1495011517927, NULL, NULL, NULL, NULL, NULL, NULL, '联网录像分析|删除/批量删除', NULL, NULL, '删除/批量删除', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'analysis.onlinecamera.delete,analysis.onlinecamera.batchdelete', 'button');
-- INSERT INTO `sys_module` (`module_id`, `parent_id`, `module_url`, `state`, `is_visible`, `actions`, `long_number`, `module_level`, `display_name`, `leaf`, `seq`, `module_name`, `module_number`, `module_description`, `creator_id`, `create_time`, `last_update_user_id`, `last_updated_time`, `ctrl_unit_id`, `module_icon`, `is_dsiplay`, `display_order`, `info1`, `info2`, `info3`, `perms`, `type`) VALUES (1495011517936, 1495011517927, NULL, NULL, NULL, NULL, NULL, NULL, '联网录像分析|下载', NULL, NULL, '下载', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'analysis.onlinecamera.downloadcamera', 'button');
-- INSERT INTO `sys_module` (`module_id`, `parent_id`, `module_url`, `state`, `is_visible`, `actions`, `long_number`, `module_level`, `display_name`, `leaf`, `seq`, `module_name`, `module_number`, `module_description`, `creator_id`, `create_time`, `last_update_user_id`, `last_updated_time`, `ctrl_unit_id`, `module_icon`, `is_dsiplay`, `display_order`, `info1`, `info2`, `info3`, `perms`, `type`) VALUES (1495011517937, 1495011517928, NULL, NULL, NULL, NULL, NULL, NULL, '联网实时视频分析|新增/编辑/删除/批量删除', NULL, NULL, '新增/编辑/删除/批量删除', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'analysis.onlinevideo.add,analysis.onlinevideo.edit,analysis.onlinevideo.delete,analysis.onlinevideo.batchdelete,analysis.ipc.add,analysis.ipc.edit,analysis.ipc.delete,analysis.ipc.batchdelete', 'button');
-- INSERT INTO `sys_module` (`module_id`, `parent_id`, `module_url`, `state`, `is_visible`, `actions`, `long_number`, `module_level`, `display_name`, `leaf`, `seq`, `module_name`, `module_number`, `module_description`, `creator_id`, `create_time`, `last_update_user_id`, `last_updated_time`, `ctrl_unit_id`, `module_icon`, `is_dsiplay`, `display_order`, `info1`, `info2`, `info3`, `perms`, `type`) VALUES (1495011517938, 1495011517928, NULL, NULL, NULL, NULL, NULL, NULL, '联网实时视频分析|启动/停止任务', NULL, NULL, '启动/停止任务', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'analysis.onlinevideo.start,analysis.onlinevideo.stop,analysis.ipc.start,analysis.ipc.stop', 'button');
-- INSERT INTO `sys_module` (`module_id`, `parent_id`, `module_url`, `state`, `is_visible`, `actions`, `long_number`, `module_level`, `display_name`, `leaf`, `seq`, `module_name`, `module_number`, `module_description`, `creator_id`, `create_time`, `last_update_user_id`, `last_updated_time`, `ctrl_unit_id`, `module_icon`, `is_dsiplay`, `display_order`, `info1`, `info2`, `info3`, `perms`, `type`) VALUES (1495011517941, 1495011517930, NULL, NULL, NULL, NULL, NULL, NULL, '抓拍机接入|新增/编辑/删除/批量删除', NULL, NULL, '新增/编辑/删除/批量删除', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'analysis.snapping.add,analysis.snapping.edit,analysis.snapping.delete,analysis.snapping.batchdelete', 'button');
-- INSERT INTO `sys_module` (`module_id`, `parent_id`, `module_url`, `state`, `is_visible`, `actions`, `long_number`, `module_level`, `display_name`, `leaf`, `seq`, `module_name`, `module_number`, `module_description`, `creator_id`, `create_time`, `last_update_user_id`, `last_updated_time`, `ctrl_unit_id`, `module_icon`, `is_dsiplay`, `display_order`, `info1`, `info2`, `info3`, `perms`, `type`) VALUES (1495011517942, 1495011517930, NULL, NULL, NULL, NULL, NULL, NULL, '抓拍机接入|启动/停止任务', NULL, NULL, '启动/停止任务', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'analysis.snapping.start,analysis.snapping.stop', 'button');
-- INSERT INTO `sys_module` (`module_id`, `parent_id`, `module_url`, `state`, `is_visible`, `actions`, `long_number`, `module_level`, `display_name`, `leaf`, `seq`, `module_name`, `module_number`, `module_description`, `creator_id`, `create_time`, `last_update_user_id`, `last_updated_time`, `ctrl_unit_id`, `module_icon`, `is_dsiplay`, `display_order`, `info1`, `info2`, `info3`, `perms`, `type`) VALUES (1495011517943, 1495011517920, NULL, NULL, NULL, NULL, NULL, NULL, '专项监控组|新增/编辑/删除/批量删除', NULL, NULL, '新增/编辑/删除/批量删除', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'analysis.monitorgroup.add,analysis.monitorgroup.edit,analysis.monitorgroup.delete,analysis.monitorgroup.batchdelete', 'button');
-- INSERT INTO `sys_module` (`module_id`, `parent_id`, `module_url`, `state`, `is_visible`, `actions`, `long_number`, `module_level`, `display_name`, `leaf`, `seq`, `module_name`, `module_number`, `module_description`, `creator_id`, `create_time`, `last_update_user_id`, `last_updated_time`, `ctrl_unit_id`, `module_icon`, `is_dsiplay`, `display_order`, `info1`, `info2`, `info3`, `perms`, `type`) VALUES (1495011517944, 1495011517920, NULL, NULL, NULL, NULL, NULL, NULL, '专项监控组|启动/停止任务', NULL, NULL, '启动/停止任务', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'analysis.monitorgroup.start,analysis.monitorgroup.stop', 'button');
-- INSERT INTO `sys_module` (`module_id`, `parent_id`, `module_url`, `state`, `is_visible`, `actions`, `long_number`, `module_level`, `display_name`, `leaf`, `seq`, `module_name`, `module_number`, `module_description`, `creator_id`, `create_time`, `last_update_user_id`, `last_updated_time`, `ctrl_unit_id`, `module_icon`, `is_dsiplay`, `display_order`, `info1`, `info2`, `info3`, `perms`, `type`) VALUES (1495011517945, 1495011517920, NULL, NULL, NULL, NULL, NULL, NULL, '专项监控组|移入/移出', NULL, NULL, '移入/移出', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'analysis.monitorgroup.move,analysis.monitorgroup.remove', 'button');
-- INSERT INTO `sys_module` (`module_id`, `parent_id`, `module_url`, `state`, `is_visible`, `actions`, `long_number`, `module_level`, `display_name`, `leaf`, `seq`, `module_name`, `module_number`, `module_description`, `creator_id`, `create_time`, `last_update_user_id`, `last_updated_time`, `ctrl_unit_id`, `module_icon`, `is_dsiplay`, `display_order`, `info1`, `info2`, `info3`, `perms`, `type`) VALUES (1495011517947, 1495011517921, NULL, NULL, NULL, NULL, NULL, NULL, '角色管理', NULL, NULL, '角色管理', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'system.rolemanage', 'menu');
-- INSERT INTO `sys_module` (`module_id`, `parent_id`, `module_url`, `state`, `is_visible`, `actions`, `long_number`, `module_level`, `display_name`, `leaf`, `seq`, `module_name`, `module_number`, `module_description`, `creator_id`, `create_time`, `last_update_user_id`, `last_updated_time`, `ctrl_unit_id`, `module_icon`, `is_dsiplay`, `display_order`, `info1`, `info2`, `info3`, `perms`, `type`) VALUES (1495011517948, 1495011517921, NULL, NULL, NULL, NULL, NULL, NULL, '用户管理', NULL, NULL, '用户管理', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'system.usermanage', 'menu');
-- INSERT INTO `sys_module` (`module_id`, `parent_id`, `module_url`, `state`, `is_visible`, `actions`, `long_number`, `module_level`, `display_name`, `leaf`, `seq`, `module_name`, `module_number`, `module_description`, `creator_id`, `create_time`, `last_update_user_id`, `last_updated_time`, `ctrl_unit_id`, `module_icon`, `is_dsiplay`, `display_order`, `info1`, `info2`, `info3`, `perms`, `type`) VALUES (1495011517949, 1495011517921, NULL, NULL, NULL, NULL, NULL, NULL, '组织机构', NULL, NULL, '组织机构', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'system.deptmanage', 'menu');
-- INSERT INTO `sys_module` (`module_id`, `parent_id`, `module_url`, `state`, `is_visible`, `actions`, `long_number`, `module_level`, `display_name`, `leaf`, `seq`, `module_name`, `module_number`, `module_description`, `creator_id`, `create_time`, `last_update_user_id`, `last_updated_time`, `ctrl_unit_id`, `module_icon`, `is_dsiplay`, `display_order`, `info1`, `info2`, `info3`, `perms`, `type`) VALUES (1495011517950, 1495011517921, NULL, NULL, NULL, NULL, NULL, NULL, '行政区域', NULL, NULL, '行政区域', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'system.unitmanage', 'menu');
-- INSERT INTO `sys_module` (`module_id`, `parent_id`, `module_url`, `state`, `is_visible`, `actions`, `long_number`, `module_level`, `display_name`, `leaf`, `seq`, `module_name`, `module_number`, `module_description`, `creator_id`, `create_time`, `last_update_user_id`, `last_updated_time`, `ctrl_unit_id`, `module_icon`, `is_dsiplay`, `display_order`, `info1`, `info2`, `info3`, `perms`, `type`) VALUES (1495011517951, 1495011517921, NULL, NULL, NULL, NULL, NULL, NULL, '集群管理', NULL, NULL, '集群管理', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'system.groupmanage', 'menu');
-- INSERT INTO `sys_module` (`module_id`, `parent_id`, `module_url`, `state`, `is_visible`, `actions`, `long_number`, `module_level`, `display_name`, `leaf`, `seq`, `module_name`, `module_number`, `module_description`, `creator_id`, `create_time`, `last_update_user_id`, `last_updated_time`, `ctrl_unit_id`, `module_icon`, `is_dsiplay`, `display_order`, `info1`, `info2`, `info3`, `perms`, `type`) VALUES (1495011517952, 1495011517921, NULL, NULL, NULL, NULL, NULL, NULL, '日志管理', NULL, NULL, '日志管理', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'system.logmanage', 'menu');
-- INSERT INTO `sys_module` (`module_id`, `parent_id`, `module_url`, `state`, `is_visible`, `actions`, `long_number`, `module_level`, `display_name`, `leaf`, `seq`, `module_name`, `module_number`, `module_description`, `creator_id`, `create_time`, `last_update_user_id`, `last_updated_time`, `ctrl_unit_id`, `module_icon`, `is_dsiplay`, `display_order`, `info1`, `info2`, `info3`, `perms`, `type`) VALUES (1495011517953, 1495011517921, NULL, NULL, NULL, NULL, NULL, NULL, '使用排行榜', NULL, NULL, '使用排行榜', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'system.leaderboard', 'menu');
-- INSERT INTO `sys_module` (`module_id`, `parent_id`, `module_url`, `state`, `is_visible`, `actions`, `long_number`, `module_level`, `display_name`, `leaf`, `seq`, `module_name`, `module_number`, `module_description`, `creator_id`, `create_time`, `last_update_user_id`, `last_updated_time`, `ctrl_unit_id`, `module_icon`, `is_dsiplay`, `display_order`, `info1`, `info2`, `info3`, `perms`, `type`) VALUES (1495011517930, 1495011517919, NULL, NULL, NULL, NULL, NULL, NULL, '抓拍机', NULL, NULL, '抓拍机', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'analysis.snapping', 'menu');



CREATE TABLE `tb_cron` (
  `id` bigint(32) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `cron` varchar(50) NOT NULL COMMENT 'cron表达式',
  `enable` tinyint(2) NOT NULL DEFAULT '1' COMMENT '是否启用（0：停用；1：启用）',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;
-- ----------------------------
-- Records of tb_cron
-- ----------------------------
INSERT INTO `tb_cron` VALUES ('1', '0 10 3 * * ?', '1', '2018-11-06 11:19:41');






