#!/bin/sh

curl -H "Content-Type: application/json" -XPUT 'http://127.0.0.1:9200/bike_result' -d'
{
    "mappings" : {
        "data" : {
            "properties" : {
				  "id" : { "type" : "keyword","index": "true"},
				  "serialnumber" : { "type" : "keyword","index": "true"},
				  "analysisid" : { "type" : "keyword","index": "true"},
				  "cameraid" : { "type" : "long","index": "true"},
				  "vlpr_result_id" : { "type" : "keyword","index": "true"},
				  "imgurl" : { "type" : "keyword","index": "true"},
				  "bigimgurl" : { "type" : "keyword","index": "true"},
				  "objtype" : { "type" : "long","index": "true"},
				  "maincolor_1" : { "type" : "keyword","index": "true"},
				  "maincolor_2" : { "type" : "keyword","index": "true"},
				  "maincolor_3" : { "type" : "keyword","index": "true"},
				  "upcolor_1" : { "type" : "keyword","index": "true"},
				  "upcolor_2" : { "type" : "keyword","index": "true"},
				  "upcolor_3" : { "type" : "keyword","index": "true"},
				  "lowcolor_1" : { "type" : "keyword","index": "true"},
				  "lowcolor_2" : { "type" : "keyword","index": "true"},
				  "lowcolor_3" : { "type" : "keyword","index": "true"},
				  "maincolorTag1" : { "type" : "long","index": "true"},
				  "maincolorTag2" : { "type" : "long","index": "true"},
				  "maincolorTag3" : { "type" : "long","index": "true"},
				  "upcolorTag1" : { "type" : "long","index": "true"},
				  "upcolorTag2" : { "type" : "long","index": "true"},
				  "upcolorTag3" : { "type" : "long","index": "true"},
				  "lowcolorTag1" : { "type" : "keyword","index": "true"},
				  "lowcolorTag2" : { "type" : "keyword","index": "true"},
				  "lowcolorTag3" : { "type" : "keyword","index": "true"},
				  "sex" : { "type" : "long","index": "true"},
				  "age" : { "type" : "long","index": "true"},
				  "wheels" : { "type" : "long","index": "true"},
				  "size" : { "type" : "keyword","index": "true"},
				  "bag" : { "type" : "long","index": "true"},
				  "glasses" : { "type" : "long","index": "true"},
				  "umbrella" : { "type" : "long","index": "true"},
				  "umbrella_color_tag" : { "type" : "keyword","index": "true"},
				  "angle" : { "type" : "long","index": "true"},
				  "handbag" : { "type" : "long","index": "true"},
				  "tubeid" : { "type" : "long","index": "true"},
				  "objid" : { "type" : "long","index": "true"},
				  "startframeidx" : { "type" : "long","index": "true"},
				  "endframeidx" : { "type" : "long","index": "true"},
				  "startframepts" : { "type" : "long","index": "true"},
				  "endframepts" : { "type" : "long","index": "true"},
				  "frameidx" : { "type" : "long","index": "true"},
				  "width" : { "type" : "long","index": "true"},
				  "height" : { "type" : "long","index": "true"},
				  "x" : { "type" : "keyword","index": "true"},
				  "y" : { "type" : "keyword","index": "true"},
				  "w" : { "type" : "keyword","index": "true"},
				  "h" : { "type" : "keyword","index": "true"},
				  "distance" : { "type" : "keyword","index": "true"},
				  "featuredataurl" : { "type" : "keyword","index": "true"},
				  "faceImgurl" : { "type" : "keyword","index": "true"},
				  "humanfeature" : { "type" : "keyword","index": "true"},
				  "peccancy" : { "type" : "keyword","index": "true"},
				  "bikeColor" : { "type" : "long","index": "true"},
				  "bikeGenre" : { "type" : "long","index": "true"},
				  "seatingCount" : { "type" : "long","index": "true"},
				  "helmet" : { "type" : "long","index": "true"},
				  "helmetColorTag1" : { "type" : "long","index": "true"},
				  "helmetColorTag2" : { "type" : "long","index": "true"},
				  "lamShape" : { "type" : "long","index": "true"},
				  "bikeHasPlate" : { "type" : "long","index": "true"},
				  "bike_feature_json" : { "type" : "keyword","index": "true"},
				  "createtime" : { "type" : "date"},
				  "inserttime" : { "type" : "date"},
				  "sychronized" : { "type" : "keyword","index": "true"},
				  "slaveip" : { "type" : "keyword","index": "true"},
				  "coatStyle" : { "type" : "keyword","index": "true"},
				  "trousersStyle" : { "type" : "keyword","index": "true"},
				  "taskid" : { "type" : "long","index": "true"},
				  "upcolorTag" : { "type" : "long","index": "true"},
				  "lowcolorTag" : { "type" : "keyword","index": "true"},
				  "maincolorTag" : { "type" : "long","index": "true"},
				  "respirator" : { "type" : "long","index": "true"},
				  "cap" : { "type" : "long","index": "true"},
				  "hairStyle" : { "type" : "long","index": "true"},
				  "coatTexture" : { "type" : "long","index": "true"},
				  "trousersTexture" : { "type" : "long","index": "true"},
				  "xywh" : { "type" : "keyword","index": "true"}
            }
        }
    }
}'
curl -H "Content-Type: application/json" -XPUT 'http://127.0.0.1:9200/face_result' -d'
{
    "mappings" : {
        "data" : {
            "properties" : {
				  "id" : { "type" : "keyword","index": "true"},
				  "serialnumber" : { "type" : "keyword","index": "true"},
				  "analysisid" : { "type" : "keyword","index": "true"},
				  "frameidx" : { "type" : "keyword","index": "true"},
				  "imgurl" : { "type" : "keyword","index": "true"},
				  "qualityscore" : { "type" : "keyword","index": "true"},
				  "horizontalangle" : { "type" : "keyword","index": "true"},
				  "verticalangle" : { "type" : "keyword","index": "true"},
				  "rotatingangle" : { "type" : "keyword","index": "true"},
				  "glass" : { "type" : "long","index": "true"},
				  "age" : { "type" : "long","index": "true"},
				  "sex" : { "type" : "long","index": "true"},
				  "nation" : { "type" : "keyword","index": "true"},
				  "x" : { "type" : "keyword","index": "true"},
				  "y" : { "type" : "keyword","index": "true"},
				  "w" : { "type" : "keyword","index": "true"},
				  "h" : { "type" : "keyword","index": "true"},
				  "featuredataurl" : { "type" : "keyword","index": "true"},
				  "createtime" : { "type" : "date"},
				  "cameraid" : { "type" : "long","index": "true"}
            }
        }
    }
}'
curl -H "Content-Type: application/json" -XPUT 'http://127.0.0.1:9200/objext_result' -d'
{
    "mappings" : {
        "data" : {
            "properties" : {
                  "id" : { "type" : "keyword","index": "true"},
				  "serialnumber" : { "type" : "keyword","index": "true"},
				  "analysisid" : { "type" : "keyword","index": "true"},
				  "cameraid" : { "type" : "long","index": "true"},
				  "vlpr_result_id" : { "type" : "keyword","index": "true"},
				  "imgurl" : { "type" : "keyword","index": "true"},
				  "bigimgurl" : { "type" : "keyword","index": "true"},
				  "objtype" : { "type" : "long","index": "true"},
				  "maincolor_1" : { "type" : "keyword","index": "true"},
				  "maincolor_2" : { "type" : "keyword","index": "true"},
				  "maincolor_3" : { "type" : "keyword","index": "true"},
				  "upcolor_1" : { "type" : "keyword","index": "true"},
				  "upcolor_2" : { "type" : "keyword","index": "true"},
				  "upcolor_3" : { "type" : "keyword","index": "true"},
				  "lowcolor_1" : { "type" : "keyword","index": "true"},
				  "lowcolor_2" : { "type" : "keyword","index": "true"},
				  "lowcolor_3" : { "type" : "keyword","index": "true"},
				  "maincolorTag1" : { "type" : "long","index": "true"},
				  "maincolorTag2" : { "type" : "long","index": "true"},
				  "maincolorTag3" : { "type" : "long","index": "true"},
				  "upcolorTag1" : { "type" : "long","index": "true"},
				  "upcolorTag2" : { "type" : "long","index": "true"},
				  "upcolorTag3" : { "type" : "long","index": "true"},
				  "lowcolorTag1" : { "type" : "long","index": "true"},
				  "lowcolorTag2" : { "type" : "long","index": "true"},
				  "lowcolorTag3" : { "type" : "long","index": "true"},
				  "sex" : { "type" : "long","index": "true"},
				  "age" : { "type" : "long","index": "true"},
				  "wheels" : { "type" : "long","index": "true"},
				  "size" : { "type" : "keyword","index": "true"},
				  "bag" : { "type" : "long","index": "true"},
				  "glasses" : { "type" : "long","index": "true"},
				  "umbrella" : { "type" : "long","index": "true"},
				  "umbrella_color_tag" : { "type" : "keyword","index": "true"},
				  "angle" : { "type" : "long","index": "true"},
				  "handbag" : { "type" : "long","index": "true"},
				  "tubeid" : { "type" : "long","index": "true"},
				  "objid" : { "type" : "long","index": "true"},
				  "startframeidx" : { "type" : "long","index": "true"},
				  "endframeidx" : { "type" : "long","index": "true"},
				  "startframepts" : { "type" : "long","index": "true"},
				  "endframepts" : { "type" : "long","index": "true"},
				  "frameidx" : { "type" : "long","index": "true"},
				  "width" : { "type" : "long","index": "true"},
				  "height" : { "type" : "long","index": "true"},
				  "x" : { "type" : "keyword","index": "true"},
				  "y" : { "type" : "keyword","index": "true"},
				  "w" : { "type" : "keyword","index": "true"},
				  "h" : { "type" : "keyword","index": "true"},
				  "distance" : { "type" : "keyword","index": "true"},
				  "featuredataurl" : { "type" : "keyword","index": "true"},
				  "faceImgurl" : { "type" : "keyword","index": "true"},
				  "humanfeature" : { "type" : "keyword","index": "true"},
				  "peccancy" : { "type" : "keyword","index": "true"},
				  "bikeColor" : { "type" : "long","index": "true"},
				  "bikeGenre" : { "type" : "long","index": "true"},
				  "seatingCount" : { "type" : "long","index": "true"},
				  "helmet" : { "type" : "long","index": "true"},
				  "helmetColorTag1" : { "type" : "long","index": "true"},
				  "helmetColorTag2" : { "type" : "long","index": "true"},
				  "lamShape" : { "type" : "long","index": "true"},
				  "bikeHasPlate" : { "type" : "long","index": "true"},
				  "bike_feature_json" : { "type" : "keyword","index": "true"},
				  "createtime" : { "type" : "date"},
				  "inserttime" : { "type" : "date"},
				  "sychronized" : { "type" : "keyword","index": "true"},
				  "slaveip" : { "type" : "keyword","index": "true"},
				  "coatStyle" : { "type" : "keyword","index": "true"},
				  "trousersStyle" : { "type" : "keyword","index": "true"},
				  "taskid" : { "type" : "long","index": "true"},
				  "upcolorTag" : { "type" : "long","index": "true"},
				  "lowcolorTag" : { "type" : "long","index": "true"},
				  "maincolorTag" : { "type" : "long","index": "true"},
				  "respirator" : { "type" : "long","index": "true"},
				  "cap" : { "type" : "long","index": "true"},
				  "hairStyle" : { "type" : "long","index": "true"},
				  "coatTexture" : { "type" : "long","index": "true"},
				  "trousersTexture" : { "type" : "long","index": "true"},
				  "xywh" : { "type" : "keyword","index": "true"}
            }
        }
    }
}'
curl -H "Content-Type: application/json" -XPUT 'http://127.0.0.1:9200/summary_result' -d'
{
    "mappings" : {
        "data" : {
            "properties" : {
				  "id" : { "type" : "keyword","index": "true"},
				  "serialnumber" : { "type" : "keyword","index": "true"},
				  "analysisid" : { "type" : "keyword","index": "true"},
				  "cameraid" : { "type" : "long","index": "true"},
				  "imgurl" : { "type" : "keyword","index": "true"},
				  "bigimgurl" : { "type" : "keyword","index": "true"},
				  "objtype" : { "type" : "long","index": "true"},
				  "tubeid" : { "type" : "long","index": "true"},
				  "objid" : { "type" : "long","index": "true"},
				  "startframeidx" : { "type" : "long","index": "true"},
				  "endframeidx" : { "type" : "long","index": "true"},
				  "startframepts" : { "type" : "long","index": "true"},
				  "endframepts" : { "type" : "long","index": "true"},
				  "frameidx" : { "type" : "long","index": "true"},
				  "width" : { "type" : "long","index": "true"},
				  "height" : { "type" : "long","index": "true"},
				  "x" : { "type" : "keyword","index": "true"},
				  "y" : { "type" : "keyword","index": "true"},
				  "w" : { "type" : "keyword","index": "true"},
				  "h" : { "type" : "keyword","index": "true"},
				  "distance" : { "type" : "keyword","index": "true"},
				  "createtime" : { "type" : "date"},
				  "inserttime" : { "type" : "date"},
				  "slaveip" : { "type" : "keyword","index": "true"},
				  "xywh" : { "type" : "keyword","index": "true"},
				  "faceImgurl" : { "type" : "keyword","index": "true"},
				  "taskid" : { "type" : "long","index": "true"}
            }
        }
    }
}'
curl -H "Content-Type: application/json" -XPUT 'http://127.0.0.1:9200/vlpr_result' -d'
{
    "mappings" : {
        "data" : {
            "properties" : {
                  "id" : { "type" : "keyword","index": "true"},
				  "serialnumber" : { "type" : "keyword","index": "true"},
				  "analysisid" : { "type" : "keyword","index": "true"},
				  "objtype" : { "type" : "long","index": "true"},
				  "taskid" : { "type" : "long","index": "true"},
				  "isObjextResult" : { "type" : "keyword","index": "true"},
				  "serialNum" : { "type" : "keyword","index": "true"},
				  "cameraid" : { "type" : "long","index": "true"},
				  "license" : { "type" : "keyword","index": "true"},
				  "licenseattribution" : { "type" : "keyword","index": "true"},
				  "platecolor" : { "type" : "keyword","index": "true"},
				  "platetype" : { "type" : "long","index": "true"},
				  "confidence" : { "type" : "long","index": "true"},
				  "bright" : { "type" : "keyword","index": "true"},
				  "direction" : { "type" : "long","index": "true"},
				  "locationLeft" : { "type" : "keyword","index": "true"},
				  "locationTop" : { "type" : "keyword","index": "true"},
				  "locationRight" : { "type" : "keyword","index": "true"},
				  "locationBottom" : { "type" : "keyword","index": "true"},
				  "costTime" : { "type" : "keyword","index": "true"},
				  "carBright" : { "type" : "keyword","index": "true"},
				  "carcolor" : { "type" : "keyword","index": "true"},
				  "carlogo" : { "type" : "keyword","index": "true"},
				  "bigimgurl" : { "type" : "keyword","index": "true"},
				  "imgurl" : { "type" : "keyword","index": "true"},
				  "imageURL" : { "type" : "keyword","index": "true"},
				  "inserttime" : { "type" : "date"},
				  "createtime" : { "type" : "date"},
				  "carspeed" : { "type" : "keyword","index": "true"},
				  "labelInfoData" : { "type" : "keyword","index": "true"},
				  "vehicleKind" : { "type" : "keyword","index": "true"},
				  "vehicleBrand" : { "type" : "keyword","index": "true"},
				  "vehicleSeries" : { "type" : "keyword","index": "true"},
				  "vehicleStyle" : { "type" : "keyword","index": "true"},
				  "vehicleResion" : { "type" : "keyword","index": "true"},
				  "tag" : { "type" : "long","index": "true"},
				  "paper" : { "type" : "long","index": "true"},
				  "sun" : { "type" : "long","index": "true"},
				  "hasDrop" : { "type" : "long","index": "true"},
				  "hasCall" : { "type" : "long","index": "true"},
				  "crash" : { "type" : "long","index": "true"},
				  "danger" : { "type" : "long","index": "true"},
				  "mainBelt" : { "type" : "long","index": "true"},
				  "secondBelt" : { "type" : "long","index": "true"},
				  "sunRoof" : { "type" : "long","index": "true"},
				  "spareTire" : { "type" : "long","index": "true"},
				  "rack" : { "type" : "long","index": "true"},
				  "width" : { "type" : "long","index": "true"},
				  "height" : { "type" : "long","index": "true"},
				  "unitIdentity" : { "type" : "keyword","index": "true"},
				  "retrycount" : { "type" : "long","index": "true"},
				  "frameIdx" : { "type" : "long","index": "true"},
				  "LocationInfo" : { "type" : "keyword","index": "true"},
				  "xywh" : { "type" : "keyword","index": "true"},
				  "vehicleLeft" : { "type" : "keyword","index": "true"},
				  "vehicleTop" : { "type" : "keyword","index": "true"},
				  "vehicleRight" : { "type" : "keyword","index": "true"},
				  "vehicleBootom" : { "type" : "keyword","index": "true"},
				  "vehicleConfidence" : { "type" : "long","index": "true"},
				  "face" : { "type" : "keyword","index": "true"},
				  "face_url1" : { "type" : "keyword","index": "true"},
				  "face_url2" : { "type" : "keyword","index": "true"},
				  "vehicleUrl" : { "type" : "keyword","index": "true"},
				  "featuredataurl" : { "type" : "keyword","index": "true"},
				  "peccancy" : { "type" : "keyword","index": "true"},
				  "objid" : { "type" : "long","index": "true"},
				  "startframepts" : { "type" : "long","index": "true"},
				  "endframepts" : { "type" : "long","index": "true"},
				  "startframeidx" : { "type" : "long","index": "true"},
				  "endframeidx" : { "type" : "long","index": "true"},
				  "sychronized" : { "type" : "keyword","index": "true"},
				  "slaveip" : { "type" : "keyword","index": "true"}
            }
        }
    }
}'