version: '2'
services:
  task-task:
    image: task-base:2.0.3.36.jt
    container_name: task-task1
    network_mode: "host"
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    build: .
    env_file:
      - ../env/nacos/nacos.env
      - java.env
    volumes:
      - /logs/task/:/logs/
      - /u2s/task/task/keensense-task.jar:/home/task/task.jar
      - /logs/config/logback-spring.xml:/logs/config/logback-spring.xml
      - /u2s/task/task/deletePictureBySernum.sh:/home/task/deletePictureBySernum.sh
      - /u2s/slave/objext/objext/:/home/task/objext/
      - /logs/jdk_tools/:/logs/jdk_tools/
    cap_add:
      - SYS_PTRACE


