# 数据源   192.168.0.66:3306  192.168.0.143
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:  Ast4HS
    url: jdbc:mysql://192.168.0.66:3306/u2s?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false


vas-server:
    ip: 192.168.0.143
    port: 8350
    username: admin
    password: admin

vas-url:
    name: admin
    psw: 1234
    srvip: 192.168.0.143
    srvport: 8350

cleanvas-url:
  url: http://127.0.0.1:8088/u2s/rest/cleanVasCameraCache

#mybaits-plus配置，修改主键类型，mapper.xml、type 别名等
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: false
    # 逻辑删除字段
    logic-delete-value: 1
    logic-not-delete-value: 0
    #自定义SQL注入器
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
